# Generated by Django 4.2.1 on 2023-05-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('Django', 'Django'), ('Full Stack', 'Full Stack'), ('Others', 'Others')], default='Java', max_length=20, verbose_name='Preffered Course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(help_text='Email should contain @ symbol', max_length=254, verbose_name='Enter Email Id'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(help_text='Name should be within 30 letters', max_length=30, verbose_name='Enter Name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(help_text='Phone Number should contain 10 digits', verbose_name='Enter Mobile Number'),
        ),
    ]
